### ISSUE TITLE
conflict between libpcl armhf and existing debs when I try to import

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/reprepro-updater#15]
```
rosbuild@p:~/reprepro_updater/armhf$ python /home/rosbuild/reprepro_updater/scripts/prepare_sync.py /var/www/repos/ros-shadow-fixed/ubuntu -y /home/rosbuild/reprepro_updater/config/namniart_armhf.yaml -c
Updating for trusty armhf to update into repo /var/www/repos/ros-shadow-fixed/ubuntu
I have a lock on /var/www/repos/ros-shadow-fixed/ubuntu/lock
Creating updates file /var/www/repos/ros-shadow-fixed/ubuntu/conf/updates
Creating distributions file /var/www/repos/ros-shadow-fixed/ubuntu/conf/distributions
running command ['reprepro', '-v', '-b', '/var/www/repos/ros-shadow-fixed/ubuntu', '--noskipold', 'update', 'trusty']
Warning: No VerifyRelease line in 'namniart_armhf_bootstrap' or any rule it includes via 'From:'.
Release.gpg cannot be checked unless you tell which key to check with.
(To avoid this warning and not check signatures add 'VerifyRelease: blindtrust').
aptmethod got 'http://23.239.1.142/repos/ros_support/dists/trusty/Release'
Calculating packages to get...
File "pool/main/p/pcl-1.7/libpcl-1.7-all_1.7.1-3+trusty2_all.deb" is already registered with different checksums!
md5 expected: c18e8527e3369e486dcac0b029490b81, got: 9cfb6edfc2c305f7d0a23d1b42e882a3
sha1 expected: 56c5415d80f1566b64172857b8930c59c3df52ef, got: ce2431549434fb702dbd1aa1a512723f4279b08b
sha256 expected: 30b987ebe82e422795794ed68037ad390a7a126adb0fc39b75f4f61afd8f1899, got: 21ecc08a96dfcd1a2837ae3412ea2a945dd3f6bd180ccd5f77ba975583e639cf
There have been errors!
Traceback (most recent call last):
  File "/home/rosbuild/reprepro_updater/scripts/prepare_sync.py", line 166, in <module>
    run_update(repo_dir, dist, updates_generator, 'rosdistro_na', distro, arch, options.commit)
  File "/home/rosbuild/reprepro_updater/scripts/prepare_sync.py", line 56, in run_update
    subprocess.check_call(update_command)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['reprepro', '-v', '-b', '/var/www/repos/ros-shadow-fixed/ubuntu', '--noskipold', 'update', 'trusty']' returned non-zero exit status 254
```

@trainman419 FYI I didn't run into this on the test farm. I'm not sure what's different here. For now I've skipped pcl for testing.

**Comment by tfoote** [comment]
This is a problem still because the libpcl-1.7-all is the rosdep definition for pcl. So I can't install pcl_ros etc. I've tested installing the upstream arch independant one. I think we'll need to flood it across from the other arches.

**Comment by tfoote** [comment]
Note all needs all-dev and doc we'll need to flood all 3
